"""empty message

Revision ID: 9a6296c7e72c
Revises: 
Create Date: 2020-03-04 19:30:33.937815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6296c7e72c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('env_var',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('label')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('var_val', sa.Integer(), nullable=True),
    sa.Column('env_var_id', sa.String(), nullable=True),
    sa.Column('shelf_id', sa.Integer(), nullable=True),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('arduino_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['env_var_id'], ['env_var.label'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_Val', sa.Integer(), nullable=True),
    sa.Column('time_from', sa.DateTime(), nullable=True),
    sa.Column('time_to', sa.DateTime(), nullable=True),
    sa.Column('env_var_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['env_var_id'], ['env_var.label'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.DateTime(), nullable=True),
    sa.Column('env_var_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['env_var_id'], ['env_var.label'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target_cycle')
    op.drop_table('target')
    op.drop_table('readings')
    op.drop_table('user')
    op.drop_table('env_var')
    # ### end Alembic commands ###
